version = 1

exclude_patterns = [
  'core/migrations/*',
]

test_patterns = [
  "tests/test_*.py"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "2.x.x"

  [analyzers.meta]
  max_line_length = 100
  skip_doc_coverage = ["module", "magic", "class"]
